$(document).ready(function(){
	$(".dianji").click(function(){
		$(".mm").show();
		$(this).hide();
		$(".dianji1").show();
	});
	$(".dianji1").click(function(){
		$(".mm").hide();
		$(this).hide();
		$(".dianji").show();
	});
	$(".zuixinp").css("color","#fd5238");
	$(".xiabiao").show();
	$(".zuixinp").click(function(){
		$(".main_mm").show();
		$(".main_mm1").hide();
		$(".zuixinp1").css("color","#bebbcc");
		$(".xiabiao1").hide();
	});
	$(".zuixinp1").click(function(){
		$(".main_mm").hide();
		$(".main_mm1").show();
		$(".zuixinp1").css("color","#fd5238");
		$(".zuixinp").css("color","#bebbcc");
		$(".xiabiao1").show();
		$(".xiabiao").hide();
	});
		$(".dianji11").click(function(){
		$(".mm1").show();
		$(this).hide();
		$(".dianji1").show();
	});
	$(".dianji111").click(function(){
		$(".mm1").hide();
		$(this).hide();
		$(".dianji").show();
	});
})
